spring:
  application:
    name: spring-course

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true

    open-in-view: false


logging:
  level:
    # root: WARN
    br.com.sobreiraromulo: DEBUG